Traceback (most recent call last):
  File "/Users/tachyon/Desktop/pyro-venv/pyro-venv/miniforge_x86_64/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/tachyon/Desktop/pyro-venv/pyro-venv/miniforge_x86_64/lib/python3.9/site-packages/nbclient/client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/tachyon/Desktop/pyro-venv/pyro-venv/miniforge_x86_64/lib/python3.9/site-packages/nbclient/util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/tachyon/Desktop/pyro-venv/pyro-venv/miniforge_x86_64/lib/python3.9/site-packages/nbclient/util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "/Users/tachyon/Desktop/pyro-venv/pyro-venv/miniforge_x86_64/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/tachyon/Desktop/pyro-venv/pyro-venv/miniforge_x86_64/lib/python3.9/site-packages/nbclient/client.py", line 558, in async_execute
    await self.async_execute_cell(
  File "/Users/tachyon/Desktop/pyro-venv/pyro-venv/miniforge_x86_64/lib/python3.9/site-packages/nbclient/client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/tachyon/Desktop/pyro-venv/pyro-venv/miniforge_x86_64/lib/python3.9/site-packages/nbclient/client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
title= "parameter distribution for : %s"%(chain)
fig = ff.create_distplot(list(prior_samples.values()), list(prior_samples.keys()))
fig.update_layout(title="Prior distribution of parameters", xaxis_title="parameter values", yaxis_title="density", legend_title="parameters")
fig.show()

print("Prior alpha Q(0.5) :%s | Prior beta Q(0.5) :%s"%(np.quantile(prior_samples["alpha"], 0.5), np.quantile(prior_samples["beta"], 0.5)))

------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-7-7f0456218aba>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mtitle[0m[0;34m=[0m [0;34m"parameter distribution for : %s"[0m[0;34m%[0m[0;34m([0m[0mchain[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0mfig[0m [0;34m=[0m [0mff[0m[0;34m.[0m[0mcreate_distplot[0m[0;34m([0m[0mlist[0m[0;34m([0m[0mprior_samples[0m[0;34m.[0m[0mvalues[0m[0;34m([0m[0;34m)[0m[0;34m)[0m[0;34m,[0m [0mlist[0m[0;34m([0m[0mprior_samples[0m[0;34m.[0m[0mkeys[0m[0;34m([0m[0;34m)[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0mfig[0m[0;34m.[0m[0mupdate_layout[0m[0;34m([0m[0mtitle[0m[0;34m=[0m[0;34m"Prior distribution of parameters"[0m[0;34m,[0m [0mxaxis_title[0m[0;34m=[0m[0;34m"parameter values"[0m[0;34m,[0m [0myaxis_title[0m[0;34m=[0m[0;34m"density"[0m[0;34m,[0m [0mlegend_title[0m[0;34m=[0m[0;34m"parameters"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0mfig[0m[0;34m.[0m[0mshow[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0;34m[0m[0m

[0;31mNameError[0m: name 'chain' is not defined
NameError: name 'chain' is not defined

